spring.application.name=school_management

spring.datasource.password=java@123
spring.datasource.url=jdbc:postgresql://localhost:5432/java_db
spring.datasource.username=javauser

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=9000